const stormData = {
  main: {
    description: `The term "geomagnetic storm" refers to a significant disruption of Earth's magnetosphere that happens when there is a very effective transfer of energy from the solar wind into the surrounding space environment. A solar coronal mass ejection (CME) or, less dangerously, a co-rotating interaction region (CIR), a fast-moving stream of solar wind coming from a coronal hole, could be the disturbance that propels the magnetic storm. The sunspot cycle affects the frequency of geomagnetic storms, both positively and negatively. Geomagnetic storms are more common at solar maxima, and most of them are caused by CMEs. Magnetosphere compression begins with an increase in solar wind pressure. Increased energy is transferred into the magnetosphere by the interaction between the Earth's magnetic field and the solar wind's magnetic field. Both interactions result in an increase in electric current in the magnetosphere and ionosphere as well as an increase in plasma mobility through the magnetosphere (caused by increasing electric fields inside the magnetosphere). The magnetosphere's electric current produces a magnetic force that pushes out the magnetosphere's boundary with the solar wind during a geomagnetic storm's main phase. CMEs typically take several days to arrive at Earth, but have been observed, for some of the most intense storms, to arrive in as short as 18 hours. Another solar wind disturbance that creates conditions favorable to geomagnetic storms is a high-speed solar wind stream (HSS). HSSs plow into the slower solar wind in front and create co-rotating interaction regions, or CIRs. These regions are often related to geomagnetic storms that while less intense than CME storms, often can deposit more energy in Earth’s magnetosphere over a longer interval.`,
    "Phases of geomagnetic storm": {
      description: "There are three phases to a geomagnetic storm: initial, major, and recuperation. Dst, or its one-minute component SYM-H, increases by 20 to 50 nT in tens of minutes, which is indicative of the first phase. The first stage is also known as a storm sudden beginning (SSC). But not every abrupt spike in Dst or SYM-H is followed by a geomagnetic storm, and not every geomagnetic storm has an early phase. When Dst falls to less than -50 nT, a geomagnetic storm is said to be in its main phase. The storm definition of −50 nT is chosen somewhat arbitrarily. During a storm, the minimum value will be between -50 and around -600 nT. Usually, the major phase lasts between two and eight hours. Dst transitions from its minimal value to its quiet time value throughout the recovery phase. The recuperation period could be for seven days or just eight hours. A geomagnetic storm can be categorised as a moderate storm (\\50 nT > minimum of Dst > 100 nT), an intense storm (−100 nT > minimum Dst > 250 nT), or a superstorm (minimum of Dst < −250 nT)."
    },
    Consequences: {
      description: "According to a NASA statement, electrically charged gases produce magnetic fields by creating electrical currents that function as a magnetic dynamo inside the sun. The tumultuous nature of the gases that form these magnetic fields causes them to twist, tangle, and reorganise themselves, according to NASA Space Place. This unstable magnetic field behaviour, sometimes referred to as solar activity, has the ability to cause solar flare eruptions, which unleash enormous amounts of electromagnetic radiation, which is a type of energy that comprises visible light, X-rays, microwaves, radio waves, and gamma rays from the surface.",
      "Solar flares": "Solar flares are large explosions from the surface of the sun that emit intense bursts of electromagnetic radiation. The intensity of the explosion determines what classification the flare belongs to. The most powerful are X-class flares, followed by M-, C- and B-class; A-class flares are the smallest. Solar flares occur when magnetic energy builds up in the solar atmosphere and is released suddenly. These outbursts are intrinsically linked to the solar cycle — an approximately 11-year cycle of solar activity driven by the sun's magnetic field. We are in solar cycle 25, which means that solar activity is increasing. The solar maximum is expected to happen in 2025. SpaceWeatherLive.com records the most recent 24-hour solar X-ray data from the primary GOES-16 satellite and displays such activity in helpful graphs along with the percentage chance of various types of solar flares. This allows users to stay up to date on space weather findings and determine whether there is a solar flare today. The NOAA categorises solar flares into five groups. The intensity of the X-rays they emit determines their classification. Much to the Richter scale, which indicates the intensity of an earthquake, each class letter denotes a ten-fold increase in energy production. The strongest solar flares, according to NASA, are X-class flares. After that, there are flares classified as M-class, which are ten times smaller than X-class flares, C-class, B-class, and lastly A-class, which are too weak to have a noticeable impact on Earth. A narrower scale, ranging from 1 to 9, allows for better precision in the flare assessment within each letter class; larger numbers indicate more strong flares within the class.However, X-class flares can break this nine-point rating mold with higher ratings, since there is no class more powerful than X-class. According to NASA, a 2003 solar flare was so powerful it overloaded the sensors measuring it. The sensors reported an X28 flare before cutting out.\n\n Fortunately, X-class flares occur on average about 10 times per year, and flares as powerful as the one recorded in 2003 are even less likely.",
      "Classification of solar flares":`Various types of solar flares, particularly X-class flares, have a significant impact on Earth, satellites, and astronauts.A and B-class flares are the weakest and most common types, lacking the intensity to affect Earth meaningfully. C-class flares are also weak and generally have little to no effect on our planet. In contrast, M-class flares are stronger and can trigger coronal mass ejections (CMEs) that disrupt Earth's magnetosphere. X-class flares, being the most powerful, are capable of causing severe geomagnetic storms and significant disruptions.These geomagnetic storms can result from M-class and X-class flares, allowing auroras to be visible further south than usual. A notable incident in 1989 saw a blackout in Quebec due to a geomagnetic storm triggered by a solar flare. Additionally, these flares can lead to radio blackouts that primarily affect High Frequency (HF) communications. The increased electron density in the ionosphere during a flare causes radio waves to lose energy, hindering effective communication.Solar flares can also damage satellites by exposing them to high-energy particles, which may temporarily disrupt communication and GPS satellites. During intense solar activity, satellite operators must closely monitor orbits since CMEs can expand the atmosphere, increasing drag on satellites and potentially lowering their orbits.For astronauts aboard the International Space Station (ISS), there are risks from high-energy particles during solar storms. They must take shelter within the spacecraft during these events to avoid exposure. Interestingly, during solar flares, the amount of cosmic radiation encountered by astronauts may decrease due to a phenomenon known as the "Forbush decrease," where solar particles push away other cosmic rays.In summary, while A and B-class flares pose minimal risks, M and X-class flares can have profound effects on Earth's environment, satellite operations, and astronaut safety. Planet Earth is currently undergoing one of the most significant solar storms in decades, causing concern among those managing power grids, communication networks, and satellites. In February 2022, a Coronal Mass Ejection (CME) led to the loss of 38 commercial satellites. The solar plasma from the storm heated the atmosphere, causing denser gases to expand into the satellites' orbits, which increased atmospheric drag and ultimately caused them to de-orbit.`
    }
  },
  earth: {
    description: "The phenomenon of geomagnetic storms arises from disturbances in Earth’s magnetosphere, primarily triggered by solar activity such as coronal mass ejections (CMEs). These storms can create spectacular auroras that may be visible at lower latitudes during particularly intense events. However, they also have the potential to disrupt communication systems, especially high-frequency radio signals, and pose risks to satellites by increasing atmospheric drag and damaging their electronic components. Additionally, the electric currents generated during these storms can overload power grids, resulting in voltage fluctuations and possible blackouts. The heightened radiation levels associated with severe storms can also present risks for astronauts and passengers on high-altitude flights. In essence, while geomagnetic storms offer stunning displays in the night sky, they also pose significant challenges to modern technology and infrastructure, illustrating the intricate connections between Earth and solar activity.",
    Effects: {
      description: "The National Oceanic and Atmospheric Administration (NOAA) has observed measurable effects from the ongoing geomagnetic storm, including :",
      "Communication and navigation": "Our reliance on satellite-based technology for global communication, navigation, and surveying is increasing. Geomagnetic storms disrupt radio signals, causing fluctuations and unexpected paths, impacting public and amateur radio communications. GPS systems also suffer from time delays and inaccuracies due to ionospheric disturbances, which can lead to significant navigation errors. Solar storms can impair navigation for air and sea transport, affecting position accuracy by miles. Additionally, military detection systems may be compromised during such events, prompting the need for backup systems and maintenance alerts.",
      "Power systems": "Geomagnetic disturbances can generate enhanced currents in the magnetosphere-ionosphere system, impacting ground-based electric power systems. A notable example occurred on March 13, 1989, when a geomagnetic storm caused a nine-hour blackout affecting six million people in Montreal and parts of the northeastern U.S. These disturbances induce currents in long transmission lines, particularly at high latitudes, leading to overheating and potential damage to transformers designed for alternating current (AC). Such disruptions can significantly impact daily life, underscoring the importance of early geomagnetic storm alerts for power companies to mitigate damage and outages.",
      "Collision Risks in Low Earth Orbit": "The geomagnetic storm in May 2024, classified as G5—the most severe level—resulted in a rapid altitude decline for thousands of satellites in low Earth orbit (LEO), dropping at a rate of 590 feet (180 meters) per day. In response, many satellites fired their thrusters simultaneously to regain altitude, creating potential collision risks as tracking systems struggled to adapt to the swift changes in their paths. This storm marked the strongest solar event since 2003 and underscored the complications arising from the growing number of satellites in LEO, where more than 10,000 active payloads operate in an atmosphere increasingly affected by solar activity.",
      Aurora: "Auroras are stunning natural light displays, primarily visible at night in polar regions. The northern lights, known as aurora borealis, occur in the Arctic, while the southern lights, or aurora australis, are seen in the Antarctic. These phenomena result from solar storms—explosive bursts of electromagnetic radiation from the Sun—that send charged particles into Earth's atmosphere. When these particles collide with atmospheric gases, they produce colorful lights, with various hues depending on the gas involved. Solar activity follows an 11-year cycle, with a peak expected around July 2025, increasing aurora visibility.\n\nThese occurrences underscore the complex relationship between solar activity and its impacts on Earth, highlighting the importance of closely monitoring space weather events."
    },
    "Geomagnetic storm May 2024": {
      description: "In May 2024, Earth experienced its most powerful solar storm in over two decades, coinciding with the peak of the current solar cycle. This G5-class storm produced vibrant auroras, visible at lower latitudes than usual, due to multiple large solar flares and coronal mass ejections (CMEs) that hurled charged particles toward our planet. The storm stretched Earth's magnetic field, allowing these particles to interact with the atmosphere and create stunning light displays.",
    },
    "Impact on the Earth":{
      description: "As a result of the storm, thousands of low Earth orbit (LEO) satellites were forced to fire their thrusters simultaneously to regain altitude, leading to potential collision risks as tracking systems struggled to keep up with their changing paths. This incident marked a significant challenge for satellite operations, highlighting the increased congestion in LEO, where over 10,000 active satellites now operate.\n\nThe heightened solar activity is part of an 11-year cycle, with expectations for more intense storms as we approach solar maximum in late 2024 and early 2025. These storms can disrupt communications, damage satellites, and affect power grids. Despite these risks, the awe-inspiring auroras serve as a reminder of the Sun's powerful influence on Earth and its atmosphere.\n\nThis storm produced vibrant auroras visible at unusually low latitudes, including the southern United States and parts of Europe, making it one of the most remarkable auroral displays in recent history.\n\nThe storm disrupted various systems, including ground-based radio communications, particularly in the high-frequency band, due to increased ionospheric density. In Canada, power companies were on alert but reported no outages, unlike a previous storm in 1989 that caused significant disruptions. However, in New Zealand, precautionary measures were taken by Transpower to mitigate potential grid impacts.\n\nNotably, the storm affected satellite operations significantly. Thousands of satellites in low Earth orbit (LEO) experienced altitude loss and had to fire thrusters simultaneously to regain height, raising concerns about potential collisions as tracking systems struggled to adapt. The storm also caused temporary data transmission losses for some satellites, including the GOES-16 weather satellite.\n\nOverall, the May 2024 geomagnetic storm highlighted the increasing challenges posed by solar activity on modern technology and infrastructure as we approach the peak of the current solar cycle.",
    }
  },
  moon: {
    description: `The Sun releases a constant flow of charged particles referred to as solar wind, which interacts with the surface of the Moon. In contrast to Earth, which is shielded by a magnetic field and atmosphere, the Moon is unprotected and directly exposed to these particles, rendering it susceptible to their impact. Although the Moon does not possess a global magnetic field, it has localized magnetic regions that can protect certain areas of its surface from solar wind. These regions contribute to the formation of distinctive geological features called "lunar swirls," which are lighter patches on the Moon where solar radiation has a reduced effect.`,
    Effects: {
      "Chemical Reactions": "Solar wind plays a significant role in chemical processes on the Moon by breaking bonds in oxygen atoms found in lunar rocks. This allows those oxygen atoms to bond with hydrogen, also delivered by the solar wind, resulting in the formation of hydroxyl (OH) molecules. Understanding this process is vital for identifying potential water sources for future lunar missions.",
      "Static Electricity": "The interaction between solar wind and the lunar surface generates static electricity, which can cause astronauts and equipment to accumulate electric charges while traversing the Moon. This poses risks during missions, although solar radiation can help discharge static electricity in sunlit areas. In permanently shadowed regions, discharging static electricity becomes more difficult, necessitating innovative solutions for future exploration.",
      "Soil Activation": "Recent research indicates that geomagnetic storms may activate lunar soil at the poles, potentially releasing trapped gases and impacting future resource utilization on the Moon. This activation could have significant implications for sustainable exploration and habitation.",
      "Mission Planning": "A thorough understanding of solar activity and geomagnetic storms is essential for planning lunar missions. Predicting solar flares can help protect astronauts from harmful radiation exposure during their time on the Moon's surface.The interaction between geomagnetic storms and the Moon's environment is a crucial focus for future lunar exploration. The Moon's direct exposure to solar wind, due to its absence of a protective atmosphere and magnetic field, results in distinctive chemical reactions and challenges, such as the accumulation of static electricity. Grasping these effects is essential for ensuring astronaut safety and the success of missions aimed at utilizing lunar resources. As we enhance our exploration efforts, especially in permanently shadowed regions and polar areas, insights into geomagnetic storms will be vital for developing strategies for sustainable habitation and resource management on the Moon. This knowledge not only deepens our understanding of lunar geology but also equips us for a long-term human presence beyond Earth."
    },
    "Geomagnetic Storm May 2024": {
      description: "The geomagnetic storm that occurred in May 2024 had significant consequences for both Earth and the Moon, particularly regarding radiation exposure and its implications for lunar exploration. In early May, a series of intense solar flares and coronal mass ejections (CMEs) resulted in one of the strongest geomagnetic storms in two decades, classified as G5 on the geomagnetic storm scale. This storm was marked by remarkable auroras that could be seen at unusually low latitudes across the globe, including areas in the United States and Europe. NASA's Solar Dynamics Observatory recorded over 80 significant solar flares during this time, with several X-class flares contributing to the storm's severity.",
    },
    "Impact on the Moon": {
      "Radiation Exposure": "The Moon's lack of a protective atmosphere and magnetic field makes it highly vulnerable to solar radiation during geomagnetic storms. While the storm primarily impacted Earth, its effects on lunar missions are crucial. Elevated radiation levels pose risks to astronauts and equipment for upcoming lunar exploration efforts, such as NASA's Artemis program.",
      "Data Collection by BioSentinel":"During the storm, NASA's BioSentinel mission gathered important data on radiation exposure in deep space. Although classified as an extreme geomagnetic event on Earth, initial findings suggested that it only caused moderate increases in hazardous solar particles in deep space. This information is vital for understanding how such storms might influence life beyond Earth's protective environment.",
      "Electrically Charged Lunar Regolith":"Research indicates that solar storms can cause electrostatic charging of lunar regolith, particularly in permanently shadowed areas. This effect could complicate future lunar missions by impacting equipment and habitats due to localized heating or alterations in regolith behavior during severe solar events."
    }
  },
  mars: {
    description: "NASA's Mars Atmosphere and Volatile Evolution (MAVEN) mission has provided valuable insights into the interaction between geomagnetic storms and the atmosphere of Mars, highlighting how solar activity has impacted the planet's climate over time. The MAVEN mission has found that solar wind—a stream of charged particles from the sun—significantly contributes to the erosion of Mars' atmosphere. This atmospheric loss intensifies during solar storms, resulting in a current loss rate of about 100 grams of gas per second, which escalates during geomagnetic events.The research indicates that Mars likely possessed a denser atmosphere that could have supported liquid water, a crucial element for life. Intense solar activity billions of years ago is believed to have caused substantial atmospheric depletion, transforming Mars from a warm and wet environment into the cold, dry landscape seen today. MAVEN's data reveal that solar wind generates electric fields that accelerate ions in the upper atmosphere of Mars, causing them to escape into space. Most of these escaping ions are traced back to regions behind the planet and polar plumes, pinpointing specific areas where atmospheric loss occurs.",
    effects: {
      AtmosphericLoss: "Mars currently loses about 100 grams of atmospheric gas per second due to solar wind interaction. This rate increases significantly during geomagnetic storms.",
      HabitabilityImpact: "Geomagnetic storms and intense solar activity over billions of years have played a crucial role in Mars losing its ability to retain water, significantly impacting its potential for sustaining life.",
      IonEscape: "Solar wind accelerates ions in the Martian atmosphere, causing them to escape into space from specific areas like polar plumes. This process is a key mechanism of atmospheric erosion.",
      ClimaticTransformation: "The cumulative effect of atmospheric loss due to solar activity has transformed Mars from a potentially warm and wet environment into the cold, dry landscape observed today.",
      RadiationExposure: "The thin Martian atmosphere provides little protection against solar and cosmic radiation, posing challenges for future human exploration and colonization efforts."
    },
    may2024Storm: {
      Summary: "In May 2024, a powerful solar storm hit Mars, causing significant radiation levels and visible auroras across the planet. This event provided valuable data on the Martian environment during extreme solar activity.",
      RadiationLevels: "The Curiosity rover recorded a peak radiation level of 8,100 micrograys, equivalent to about 30 chest X-rays. This marked the highest radiation surge detected in Curiosity's 12-year operational history on Mars.",
      Auroras: "Widespread auroras spanned the entire Martian atmosphere, unlike Earth's localized auroras. This global effect is due to Mars' lack of a protective global magnetic field.",
      TechnologicalDisruptions: "Mars Odyssey experienced a brief blackout and significant degradation of its solar panels, equivalent to a year's wear in just one day. Curiosity's cameras captured visual distortions caused by energetic particles impacting their detectors.",
      AtmosphericEffects: "The storm likely caused an increase in the rate of atmospheric loss, providing real-time data on how such events contribute to Mars' long-term climate evolution.",
      ScientificInsights: "The event offered unprecedented data on how future astronauts might be affected by such storms on Mars, contributing significantly to mission planning and safety protocols for future manned missions."
    }
  }
};

export default stormData;